### ISSUE TITLE
New posts & comments immediately show two upvotes

### ISSUE THREAD

**Issue by minorsecond** [Memmy-App/memmy#252]
**Describe the bug**
After making a new comment or post, the upvote count is already at 2. However, after refreshing or viewing via web UI, the count is still 1.

**To Reproduce**
1. Create a new comment or post
2. Look at upvote count
3. See that it's already 2, immediately

**Expected behavior**
I would expect this value to be 1 after the comment or post is created.

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: iOS 16.5.1
 - Version 0.0.1 (77)

**Comment by gkasdorf** [comment]
Weird, swore this was fixed... I'll check it....again....thanks!

**Comment by minorsecond** [comment]
@gkasdorf Was it fixed in the latest TestFlight version? I hadn't updated yet when I created this report.

**Comment by minorsecond** [comment]
I just tested with 0.0.2 and it seems to be fixed.

**Comment by gkasdorf** [comment]
@minorsecond Ok. I have not actually verified yet, but feel free to re-open this if you see it happen again.

**Comment by minorsecond** [comment]
Looks like it’s still happening. 
![IMG_0752](https://github.com/gkasdorf/memmy/assets/2933789/b0c86e45-cd29-41ae-a369-6a48966743cf)

**Comment by gkasdorf** [comment]
Ah ok, looks like the particular issue is replies then now instead of just comments you have made in the past. I'll reopen and take a look here in a moment.

**Comment by minorsecond** [comment]
Thanks!

**Comment by minorsecond** [comment]
Posts are doing it as well.

**Comment by gkasdorf** [comment]
Ok here's the possibilities:

[] New reply to a post
[] New post
[] New reply to a comment
[] Comment context inside of a new reply (kind of an edge case but right now it does show an additional upvote...)
[] Same above but replying to own post (probably a bit less of an edge case)
