### ISSUE TITLE
[MEM-107] Wrong colors on browser tabs and header.

### ISSUE THREAD

**Issue by srxavi** [Memmy-App/memmy#359]
**Describe the bug**
If you set the light theme, and click on a link to open the browser, the browser window is dark. Also, if you disable "Use the system theme" change it to dark, and reenable use the system theme, if the current iOS theme is light, the system bar shows the time in white letters.

**Expected behavior**
The light/dark switch should be respected in the whole app.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 14 pro
 - OS: 16.5.1
 - Version 0.0.2 (9)

<sub>[MEM-107](https://linear.app/memmyios/issue/MEM-107/wrong-colors-on-browser-tabs-and-header)</sub>

**Comment by gkasdorf** [comment]
Issue with the system bar is fixed.

I need to look into if this is possible right now for the browser. I *think* it should follow your system setting currently, but I don't see an option to give a specific one. I'll get back to this.

**Comment by srxavi** [comment]
In my case, it does not matter if I use a dark theme or a light one, the internal browser is always dark. The only difference is that if I have selected a dark theme the status bar has a white font and if I have selected a light theme the status bar has a dark font.

**Comment by eoddc5** [comment]
Is this reproducible? @gkasdorf

**Comment by srxavi** [comment]
I have tried to delete the app, reinstall it, remove it from Settings -> General -> Storage and every time I install it, it still happens so I myself can reproduce it. Basically, no matter what theme I chose, the internal browser window is always dark.

**Comment by eoddc5** [comment]
yeah. I just tried it, too - works as explained

not a huge priority - but noted.

**Comment by gkasdorf** [comment]
This should be good to go now.
